// This file serves as a common location for all your action constants

export const ARTICLES_FETCHED = "articles.ARTICLES_FETCHED";
export const ARTICLES_FETCHING_ERROR = 'articles.ARTICLES_FETCHING_ERROR';
export const ARTICLES_REFRESHED = "articles.ARTICLES_REFRESHED";
export const ARTICLES_FILTER_CHANGED = "articles.ARTICLES_FILTER_CHANGED";
export const GUI_ARTICLE_SELECTED = "gui.GUI_ARTICLE_SELECTED";
export const GUI_IS_LOADING = "gui.GUI_IS_LOADING";
export const GUI_SET_THEME = "gui.GUI_SET_THEME";
export const GUI_SET_NOTIFICATIONS = "gui.GUI_SET_NOTIFICATIONS";
export const DISQUS_GET_COMMENTS = "disqus.DISQUS_GET_COMMENTS";
export const DISQUS_COMMENTS_FETCHING_ERROR = "disqus.DISQUS_COMMENTS_FETCHING_ERROR";
export const DISQUS_COMMENTS_FETCHED = "disqus.DISQUS_COMMENTS_FETCHED";
export const DISQUS_COMMENTS_REFRESHED = "disqus.DISQUS_COMMENTS_REFRESHED"
export const DISQUS_IS_LOADING = "disqus.DISQUS_IS_LOADING";
